//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package com.bahrunnur.monocle;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.os.Handler;
import android.util.Log;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.widget.Button;
import android.widget.ImageView;
import android.widget.TextView;
import com.bahrunnur.monocle.R.id;
import com.bahrunnur.monocle.R.layout;
import com.googlecode.androidannotations.api.BackgroundExecutor;

public final class DetailActivity_
    extends DetailActivity
{

    private Handler handler_ = new Handler();

    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        setContentView(layout.post_detail);
    }

    private void init_(Bundle savedInstanceState) {
    }

    private void afterSetContentView_() {
        mPostSummary = ((TextView) findViewById(id.post_summary));
        mPostPreviewImage = ((ImageView) findViewById(id.post_preview_image));
        mPostUserHandle = ((TextView) findViewById(id.post_user_handle));
        mPostTitle = ((TextView) findViewById(id.post_title));
        mPostReadMore = ((Button) findViewById(id.post_read_more));
        mPostStaleTime = ((TextView) findViewById(id.post_stale_time));
        mPostVotes = ((TextView) findViewById(id.post_votes));
        mPostDomain = ((TextView) findViewById(id.post_domain));
        {
            View view = findViewById(id.post_read_more);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        DetailActivity_.this.readMoreClicked();
                    }

                }
                );
            }
        }
        afterViews();
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        afterSetContentView_();
    }

    public static DetailActivity_.IntentBuilder_ intent(Context context) {
        return new DetailActivity_.IntentBuilder_(context);
    }

    @Override
    public void updatePreviewImage() {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                try {
                    DetailActivity_.super.updatePreviewImage();
                } catch (RuntimeException e) {
                    Log.e("DetailActivity_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

    @Override
    public void getPreviewImage(final String address) {
        BackgroundExecutor.execute(new Runnable() {


            @Override
            public void run() {
                try {
                    DetailActivity_.super.getPreviewImage(address);
                } catch (RuntimeException e) {
                    Log.e("DetailActivity_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, DetailActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public DetailActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (context_ instanceof Activity) {
                ((Activity) context_).startActivityForResult(intent_, requestCode);
            } else {
                context_.startActivity(intent_);
            }
        }

    }

}
